CI check documentation

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -48,22 +48,22 @@ jobs:
         run: |
           n=0
           for f in $(find . -type f -not -wholename '*/.*' -a -not -wholename '*/tests/samples/*' -a -not -wholename '*/corpus/*' -a -not -wholename '*.json'); do
-              n=$(( 1 + ${n} ))
-              filetype=$(file ${f})
-              if echo "${filetype}" | grep -q '.*text.*'; then
-                  echo "CHECK:'${filetype}'"
-                  lastbyte=$(hexdump -v -e '/1 "%02X\n"' ${f} | tail -1)
-                  echo "Last byte is '${lastbyte}'"
-                  if [ "0A" != "${lastbyte}" ]; then
-                      echo "File ${f} has inappropriate line ending"
-                      tail -1 ${f} | hexdump -C
-                  else
-                      n=$(( ${n} - 1 ))
-                  fi
+            n=$(( 1 + ${n} ))
+            filetype=$(file ${f})
+            if echo "${filetype}" | grep -q '.*text.*'; then
+              echo "CHECK:'${filetype}'"
+              lastbyte=$(hexdump -v -e '/1 "%02X\n"' ${f} | tail -1)
+              echo "Last byte is '${lastbyte}'"
+              if [ "0A" != "${lastbyte}" ]; then
+                echo "File ${f} has inappropriate line ending"
+                tail -1 ${f} | hexdump -C
               else
-                  echo "SKIP:'${filetype}'"
-                  n=$(( ${n} - 1 ))
+                n=$(( ${n} - 1 ))
               fi
+            else
+              echo "SKIP:'${filetype}'"
+              n=$(( ${n} - 1 ))
+            fi
           done
           exit ${n}
 
@@ -128,8 +128,14 @@ jobs:
           cd docs
           pip install --requirement requirements.txt
           make html
-          cd source
-          python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ./_html
+          python -m sphinx -T -E -b html -d _build/doctrees -D language=en ./source/ ./_html
+          sphinx-apidoc --force --full --ext-autodoc ../credsweeper -o source/
+          git checkout source/conf.py source/index.rst source/credsweeper.rst
+          if [ 0 -ne $(git ls-files -m | wc -l) ]; then
+            git diff
+            echo "The documentation should be updated"
+            exit 1
+          fi
 
       # # # flake8
 
@@ -139,9 +145,9 @@ jobs:
         run: |
           ERRCNT=$(flake8 credsweeper --count --exit-zero --output-file=flake8.txt)
           if ! [ 0 -eq ${ERRCNT} ] ; then
-              echo "flake8 found '${ERRCNT}' failures:"
-              cat flake8.txt
-              exit 1
+            echo "flake8 found '${ERRCNT}' failures:"
+            cat flake8.txt
+            exit 1
           fi
 
       - name: FLAKE 8 reports
@@ -164,17 +170,17 @@ jobs:
         run: |
           crc32_int=0
           for f in $(find credsweeper -iregex '.*\.\(py\|json\|yaml\|txt\|onnx\)$'); do
-              file_crc32_hex=$(crc32 $f)
-              file_crc32_int=$((16#${file_crc32_hex}))
-              crc32_int=$(( ${crc32_int} ^ ${file_crc32_int} ))
-              done
+            file_crc32_hex=$(crc32 $f)
+            file_crc32_int=$((16#${file_crc32_hex}))
+            crc32_int=$(( ${crc32_int} ^ ${file_crc32_int} ))
+            done
           version_with_crc="$(python -m credsweeper --version | head -1) crc32:$(printf '%x' ${crc32_int})"
           echo "version_with_crc = '${version_with_crc}'"
           banner=$(python -m credsweeper --banner | head -1)
           echo "banner = '${banner}'"
           if ! [ -n "${version_with_crc}" ] && [ -n "${banner}" ] && [ "${version_with_crc}" == "${banner}" ]; then
-              echo "'${version_with_crc}' != '${banner}'"
-              exit 1
+            echo "'${version_with_crc}' != '${banner}'"
+            exit 1
           fi
 
       # # # yapf
@@ -183,7 +189,7 @@ jobs:
         if: ${{ always() && steps.setup_credsweeper.conclusion == 'success' }}
         run: |
           for f in credsweeper tests docs experiment; do
-              yapf --style .style.yapf --recursive --in-place --parallel $f
+            yapf --style .style.yapf --recursive --in-place --parallel $f
           done
           if [ 0 -ne $(git ls-files -m | wc -l) ]; then
             git diff
