[skip actions] [ml] 2024-04-23T16:51:29+03:00

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,7 +22,7 @@ jobs:
       fail-fast: false
       matrix:
         os: [ ubuntu-latest, windows-latest, macos-latest ]
-        python-version: ["3.8"]
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
 
     steps:
 
@@ -66,3 +66,89 @@ jobs:
         # put the command into one line to use in various OS to avoid processing differences in new line char sequence
         pytest --random-order --random-order-bucket=global tests
 
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+
+  development_test:
+
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
+
+    steps:
+
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Install requirements
+      run: |
+        python -m pip install --upgrade pip
+        python -m pip install --requirement requirements.txt
+
+    - name: UnitTest with pytest and coverage
+      run: |
+        mkdir -vp xmlcov
+        python -m \
+          pytest \
+            --random-order \
+            --random-order-bucket=global \
+            --ignore=docs \
+            --ignore=experiment \
+            --ignore=fuzz \
+            --ignore=tests/test_app.py \
+            --cov=credsweeper \
+            --cov-report html:coverage_html/ \
+            --cov-report xml:xmlcov/coverage.xml \
+            tests \
+            ;
+
+    - name: ApplicationTest with pytest
+      run: |
+        python -m \
+          pytest \
+            --random-order \
+            --random-order-bucket=global \
+            tests/test_app.py \
+            ;
+
+    - name: Check unit-test coverage
+      run: |
+        if [ ! -f xmlcov/coverage.xml ]; then echo "xmlcov/coverage.xml does not exist"; exit 1; fi
+        COVERED=$(grep '<coverage .*>' xmlcov/coverage.xml | sed 's/.* lines-covered="\([0-9]\+\)" .*/\1/')
+        echo "COVERED=${COVERED}"
+        VALID=$(grep '<coverage .*>' xmlcov/coverage.xml | sed 's/.* lines-valid="\([0-9]\+\)" .*/\1/')
+        echo "VALID=${VALID}"
+        if [ -z "${COVERED}" ] || [ -z "${VALID}" ] || [ ${VALID} -eq 0 ]; then echo "'${VALID}' or '${COVERED}' fail"; exit 1; fi
+        COVERAGE=$(python -c "print (round(100 * ${COVERED} / ${VALID}, 2))")
+        DESCRIPTION="Coverage of lines: ${COVERED} : ${VALID} = ${COVERAGE}%"
+        echo "${DESCRIPTION}"
+        if [ $(( 1000 * ${COVERED} / ${VALID} )) -lt 800 ]; then
+            echo "Coverage should be not less than 80% !"
+            exit 1
+        else
+            echo "Satisfied coverage"
+        fi
+
+    - name: HTML coverage reports
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: coverage_html-${{ matrix.python-version }}
+        path: coverage_html
+
+    - name: Upload coverage reports to Codecov
+      if: ${{ matrix.python-version == '3.8' }}
+      uses: codecov/codecov-action@v3
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: xmlcov/coverage.xml
+
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
